flags: {}
packages:
- '.'
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Cartesian
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Michelangelo
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Leibniz
- location: C:/Users/Jonatan/Desktop/Haskell/modules/Interactive
- location: C:/Users/Jonatan/Desktop/Haskell/modules/reactive-glfw
- location:
    git: https://github.com/feuerbach/ansi-terminal.git
    commit: bf4995c7dc3ab3caa4c7051a7f1988f3a457faea
extra-deps:
- GLUtil-0.9.1.0
- hpp-0.3.1.0
- ALUT-2.4.0.2
- FTGL-2.1
- storable-tuple-0.0.3.2
- OpenAL-1.7.0.4
- reactive-banana-1.1.0.1
- pqueue-1.3.2
resolver: lts-7.0
